name: Dispatch Listener

on:
  push:
    branches:
      - main

jobs:
  # ------------------------
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Generate Matrix
        id: generate-matrix
        run: |
          SERVICES=$(cat echo.txt)
  # ------------------------
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.say_hello.outputs) }}"
  # ------------------------
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - my_echo
      - say_hello
    strategy:
      matrix:
        service: ${{ fromJSON(needs.say_hello.outputs.services) }}
    steps:
      - name: Matrix => (${{ matrix.service }}
        run: |
          echo ${{ matrix.service }}
